import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import ConvexClientProvider from "./ConvexClientProvider";
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const queryClient = new QueryClient();
    return (
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {typeof window !== 'undefined' ? (
          <QueryClientProvider client={queryClient}>
            <ConvexClientProvider>
              <Provider>
                {children}
              </Provider>
            </ConvexClientProvider>
          </QueryClientProvider>
          ): (
            <ConvexClientProvider>
              <Provider>
                {children}
              </Provider>
            </ConvexClientProvider>
          )}
        </body>
      </html>
    );
  
  // return <html><body>null</body></html>;
}
